# Example configuration.yaml entry
# NOTE: replace {BI_HOST}:{BI_PORT} with the Blue Iris server IP and Port
# https://www.home-assistant.io/components/input_select/
input_select:
  camera_dropdown:
    name: Cast camera
    options:
      - All Cameras
      - Cycle Cameras
      - Front Door
      - Front Drive
      - Garage
    initial: All Cameras
    icon: mdi:camera
  cast_to_screen_dropdown:
    name: To Screen
    options:
      - Entryway Display
      - Living Room Display
    initial: Living Room Display
    icon: mdi:cast

# https://www.home-assistant.io/components/script/
script:
  execute_cast_dropdown:
    alias: Press to execute
    sequence:
      # https://www.home-assistant.io/components/media_player/
      - service: media_player.play_media
        data_template:
          entity_id: >
            {% if is_state('input_select.cast_to_screen_dropdown', 'Entryway Display') %}
              media_player.entryway_display
            {% elif is_state('input_select.cast_to_screen_dropdown', 'Living Room Display') %}
              media_player.living_room_display
            {% endif %}
          media_content_id: >
            {% if is_state('input_select.camera_dropdown', 'Front Door') %}
              http://192.168.0.10:8081/mjpg/CAM4/video.mjpg
            {% elif is_state('input_select.camera_dropdown', 'Front Drive') %}
              http://192.168.0.10:8081/mjpg/CAM5/video.mjpg
            {% elif is_state('input_select.camera_dropdown', 'Garage') %}
              http://192.168.0.10:8081/mjpg/CAM6/video.mjpg
            {% elif is_state('input_select.camera_dropdown', 'Cycle Cameras') %}
              http://192.168.0.10:8081/mjpg/@index?/video.mjpg
            {% elif is_state('input_select.camera_dropdown', 'All Cameras') %}
              http://192.168.0.10:8081/mjpg/index?/video.mjpg
            {% endif %}
          media_content_type: "image/jpg"
